### ISSUE TITLE
Course Selection Card

### ISSUE THREAD

**Issue by firejake308** [aggie-coding-club/Automatic-Aggie-Scheduler#109]
Make this card into a React component

![course_selection_card](https://user-images.githubusercontent.com/10082177/69893046-b60d2100-12d1-11ea-8bb8-e8e6e18e8587.jpg)

**Comment by firejake308** [comment]
I'm all done with finals, so I've started work on this in the branch `frontend/course-select-card` if anyone wants to see the work in progress.

**Comment by firejake308** [comment]
Aight' I've finished what I can on this branch until the Redux commit is merged into `frontend/master`, because the card needs to use Redux to match up sections to meetings

**Comment by gannonprudhomme** [comment]
How have you been actually showing it? Do you just add it between `</AppBar>` and `<Router>` in `App.tsx`?

**Comment by firejake308** [comment]
Yeah, I also had to do the same things while I was testing it, but I didn't want to duplicate changes that were made in the  `frontend/schedule` branch to make rebasing easier. Once we rebase with the commits from `frontend/schedule`, the kebab-case will work again

**Comment by firejake308** [comment]
Also, what do you think of the basic layout? Aside from the meeting times, this is essentially what the final card will look like, but it feels too spaced out to me, at least on my tiny 13-inch screen

**Comment by gannonprudhomme** [comment]
Well the immediate thing was that I didn't realize you had been wanting to do the customization levels. While I understand the general idea by having it, I think 1) it kind of clutters up the view (although it removes clutter in some aspects), and could arguably make it more complicated and 2) we won't be able to do professor prioritization in the first round of the scheduling algo, so we should design the UI accordingly. However, we will be able to a simple yes/no to the professor, so we could provide the option to select all sections of a prof in the sections view.

Also, about the actual UI itself, the actual box should have an outline of it, as well as it should have a background that's slightly different then the main page background. Likewise: 
![chrome_iYQcEGcbLr](https://user-images.githubusercontent.com/7295783/70602435-07fb5400-1bba-11ea-9772-21af1084545a.png)

**Comment by firejake308** [comment]
>we won't be able to do professor prioritization in the first round of the scheduling algo, so we should design the UI accordingly

Do we have plans to ever implement professor prioritization? If so, we could leave the UI as it is, but ignore the priorities for now. I feel like it shouldn't be that hard, because the professor prioritization should \*theoretically\* just tell the algorithm which sections to check first, rather than arbitrarily picking one section at random to check first.

>the actual box should have an outline of it, as well as it should have a background that's slightly different then the main page background

I left the background as white, because #83 introduces a gray background for the page, and the white card will look better once that's merged in. Material cards generally don't have an outline, but they do have box shadow that I completely forgot about and will add in the next commit.

>Honors Only + Web Only aren't mutually exclusive

I'll go ahead and re-work these into checkboxes instead of radio buttons for the next commit, but do you know any actual examples of online honors classes? Or would this just be a future-proofing kinda thing?

> Can be shorter

Cool, just found a `size="small"` prop that I can use to shrink it down a bit. If that's not enough, we can also set `margin="dense"`

**Comment by gannonprudhomme** [comment]
> Do we have plans to ever implement professor prioritization? If so, we could leave the UI as it is, but ignore the priorities for now.

I mean the main thing was that it hasn't been in our designs for awhile, so I assumed we weren't going to do it anymore. I just think that it's adding something to the process that may or may not be needed, so once we have a more functioning version we can discuss if its an addition we would like to make. In other words, I don't think it's needed for the baseline of the project's feature set, and as such should be a future addition rather than starting off with it. Will wait to hear @ryan-conn 's thoughts about it.

> Material cards generally don't have an outline, but they do have box shadow that I completely forgot about and will add in the next commit.

Yeah a box shadow is fine, I really more so meant the "idea" of an outline, as in it should just show that it's a separate entity then the rest of the page. Didn't realize until further inspection of the designs that it was a box shadow rather than an outline, but box shadows should do just fine.

> but do you know any actual examples of online honors classes? Or would this just be a future-proofing kinda thing?

Nah I don't, but logically there's no reason why there wouldn't be so I say we might as well allow it. Once #94 is further down the line I can manually do a search to see if there are any though.

**Comment by ryan-conn** [comment]
> Well the immediate thing was that I didn't realize you had been wanting to do the customization levels... we won't be able to do professor prioritization in the first round of the scheduling algo, so we should design the UI accordingly. However, we will be able to a simple yes/no to the professor, so we could provide the option to select all sections of a prof in the sections view.

I think it's pretty intuitive this way rather than having switches for all the options, so I'm fine with us doing it this way

> > Do we have plans to ever implement professor prioritization? If so, we could leave the UI as it is, but ignore the priorities for now.
>
> I mean the main thing was that it hasn't been in our designs for awhile, so I assumed we weren't going to do it anymore. I just think that it's adding something to the process that may or may not be needed, so once we have a more functioning version we can discuss if its an addition we would like to make. In other words, I don't think it's needed for the baseline of the project's feature set, and as such should be a future addition rather than starting off with it. Will wait to hear @ryan-conn 's thoughts about it.

Yeah, while I like the idea of professor prioritization, there isn't a clear timeline on if/when we'll be able to implement it, so we won't need it for now. In the meantime, the professor select could either not be an option until it's implemented on the backend, or there could just a checkbox for each professor.



Here are my suggestions:
![image](https://user-images.githubusercontent.com/28655462/70751032-30d43400-1cf5-11ea-9695-cdb9df0d2ac1.png)

**Comment by ryan-conn** [comment]
One thing I forgot to mention is that if possible, I think we should use a Material UI Card as the container instead of using a custom CSS container so it can match other components better

**Comment by firejake308** [comment]
>One thing I forgot to mention is that if possible, I think we should use a Material UI Card as the container instead of using a custom CSS container so it can match other components better

I had originally used custom CSS because I didn't think Material-UI's card would support our custom header. False alarm. It does. Requested change coming next commit.

**Comment by firejake308** [comment]
@ryan-conn When you check the updated card, run `npm install` to make sure that you are using the new CSS loader. I think that fixes many of the spacing issues. Please let me know which paddings and margins feel off after you have seen the latest version.

**Comment by firejake308** [comment]
Closed by #116
