### ISSUE TITLE
Error on Scrape Courses

### ISSUE THREAD

**Issue by firejake308** [aggie-coding-club/Automatic-Aggie-Scheduler#110]
So I tried cloning @ThatJuanGuy 's `backend/scraper/course-scraping-parse-courses` branch, and I ran `python3 manage.py makemigrations`, then `python3 manage.py migrate`, then `python3 manage.py scrape_courses`, but I got this error:

> django.db.utils.ProgrammingError: column "core_curriculum" of relation "courses" does not exist

Anyone know what's up? Did I screw up a thing with Django/PostgreSQL, or is supposed to be like that?

**Comment by ThatJuanGuy** [comment]
I deleted the column because we had no plans to use it anytime soon. I had
that error also and fixed it locally. I thought I pushed the fix for that
but apparently not. Sorry. I’ll push whatever changes I’ve made whenever I
get back home which will probably be in 2-3 hours. If you want to do stuff
with it sooner, just remove the reference to the column on the
scrape_courses method where the object is being declared. It’s on the line
right before the .save(). You might also have to remove the cd and icd
column references from what I can remember.

**Comment by firejake308** [comment]
Aight no rush, I was just screwing around cuz I don't wanna study for finals

**Comment by ThatJuanGuy** [comment]
I just checked and I don't have anything I can currently commit or push on git hub desktop. I also fetched origin and there were 0 found changes. Based on this, I am now sure I pushed the bug fix a while ago. It might be an issue on your end or something caused by the rebase.

**Comment by gannonprudhomme** [comment]
Run `pip install django_extensions` then go to `autoscheduler/settings/base.py` (might be settings.py rn) and in INSTALLED_APPS add 'django_extensions'
like this:
```
INSTALLED_APPS = (
    ...
    'django_extensions',
)
```

Then run `python manage.py reset_db` + delete all of the files in `scraper/migrations`. Afterwards run `makemigrations` and `migrate` again and it *should* work

**Comment by firejake308** [comment]
Gannon's fix worked.
