### ISSUE TITLE
Unknown Professor

### ISSUE THREAD

**Issue by firejake308** [aggie-coding-club/Automatic-Aggie-Scheduler#112]
I attempted to run `python manage.py scrape_courses` on the CHEM department, but I got this error:
> django.db.utils.IntegrityError: null value in column "instructor_id" violates not-null constraint
DETAIL:  Failing row contains (482338, CHEM, 107, 509, 201931, 3, null, 0, 1, null).

I checked in Howdy, and it's a section with 1 student and zero seats, so I'm guessing the advisors made a new section to force someone in. There is no professor listed in Howdy, so I would propsoe either allowing null `instructor_id`s or treating it the same as a TBA prof

Affects PR #94

**Comment by gannonprudhomme** [comment]
Gonna wait until everyone is done with finals to actually check this out and we're working on the PR's again, since course scraping isn't done yet.

But yeah I agree, instructor should probably be null for situations like this, and we'll probably need to search for even more cases like this. That being said, I implemented scrape_courses completely on my end and I never ran into this error / didn't have to set `instructor` to null in Section, so I'm not sure how I missed this (might've done a different term tho)

**Comment by gannonprudhomme** [comment]
Now that scrape_courses is nearing finishing, can you re-check this @firejake308 ?

**Comment by gannonprudhomme** [comment]
Oh wait I'm dumb, we already fixed this as Section can now have a null instructor. I believe this is fixed.

**Comment by firejake308** [comment]
It should be, but when I tried to test it by checking out the course-scraping branch and running `python manage.py scrape_courses`, I got this error about an unclosed connection:

>SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f30abdfc908>
transport: <_SelectorSocketTransport fd=32 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
Unclosed connection
client_connection: Connection<ConnectionKey(host='compassxe-ssb.tamu.edu', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None)>

Any idea what could be causing it?

P.S. now that I think about it, I'll probably have to run `makemigrations` and `migrate` first, but those shouldn't affect the connection to Compass

**Comment by gannonprudhomme** [comment]
While I've never had that first error, I do frequently get the `Unclosed connection` error. This is an artifact of from the way we create asyncio `Session` objects (as we create a new one for each thread / department, which is over the cap of 100 so they automatically close a lot of the time). 

Eventually I want to change it so that it uses a blocking queue / bounded buffer + semaphores with a fixed amount of Sessions, but this is was the easiest way to do it and I really couldn't figure out how to not get that error (since technically I am closing the sessions, since they're in a `with` block).\

Did that first error you get cause a crash? I generally just get a bunch of unclosed connection errors.

**Comment by firejake308** [comment]
No, I also had several unclosed connections, but they all looked the same as the first, so I just posted that one. Am I just supposed to ignore these errors?

**Comment by gannonprudhomme** [comment]
Yeah just for now until I find to redo the thread creation part of `BannerRequest`, it shouldn't actually affect anything.

**Comment by firejake308** [comment]
Okay, in that case, this appears to be resolved
