### ISSUE TITLE
Outline graphic schedule components

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Automatic-Aggie-Scheduler#47]
Would incorporate the outlines for each of the basic components, i.e. the schedule table with all of the lines, the days bar at the top, an individual Meeting display, etc.

This would allow us to better divide the work on the schedule, so one person doesn't have to do all of it. Plus just to track progress on it better.

Also might want to outline Redux? Or at least give them a reference to it like #19 / the `frontend/redux-setup` branch

**Comment by firejake308** [comment]
I think the overall design process should look like:
1. Get components that look and behave the way we want them to, populated with dummy data.
2. Connect components to redux, and populate the redux store with dummy data
3. Connect redux to backend

That way we can focus on one thing at a time

**Comment by firejake308** [comment]
Setting up types would be a good first task, just to get used to TypeScript classes, but Redux itself is kinda complicated imo. I would have them learn React first, since Redux's action system is essentially a more complicated version of React's `setState`. So fill out the types first, then basic schedule, then Redux

**Comment by firejake308** [comment]
Also, in my opinion, the only components should be the `<Calendar />` and `<Meeting />`, since no other parts of `Calendar` actually have any interactivity, and thus it is difficult to justify having reactive components for something like the header or the time bar on the side. `Meeting` is a pretty good first component since it takes in props and renders them, but `Calendar` is a little more involved, so that should be done later. I think one possible strategy that would be good for learning is if I write the tests for each component and the other members write components that pass those tests.

**Comment by gannonprudhomme** [comment]
> Also, in my opinion, the only components should be the <Calendar /> and <Meeting />, since no other parts of Calendar actually have any interactivity, and thus it is difficult to justify having reactive components for something like the header or the time bar on the side

I definitely agree

> I think one possible strategy that would be good for learning is if I write the tests for each component and the other members write components that pass those tests.

That's a great idea I'm definitely down for you to do that.

Another thing, should this also include adding the MaterialUI components to `package.json` and making sure they work? Mainly b/c I had a bit of issue getting them set up on the previous repo somehow

**Comment by rconn478** [comment]
> Another thing, should this also include adding the MaterialUI components to `package.json` and making sure they work? Mainly b/c I had a bit of issue getting them set up on the previous repo somehow

I think we should make an issue for that, I could try setting it up tomorrow morning

**Comment by firejake308** [comment]
@rconn478 Sounds good, I'll try to write the tests tomorrow night after you set up Material-UI

**Comment by gannonprudhomme** [comment]
Going to close this, since #57 is basically completed
